// Generated by CoffeeScript 1.6.3
(function() {
  var Level, init;

  Level = {
    PRODUCTION: 0,
    STAGE: 1,
    DEVELOPMENT: 2
  };

  init = function(level) {
    if (level == null) {
      level = Level.PRODUCTION;
    }
    if (level > Level.PRODUCTION) {
      return console.log("Initialize script");
    }
  };

  $(function() {
    return init(Level.DEVELOPMENT);
  });

}).call(this);
