// Generated by CoffeeScript 1.6.3
(function() {
  var Level;

  Level = {
    PRODUCTION: 0,
    STAGE: 1,
    DEVELOPMENT: 2
  };

  $(function() {
    return init(Level.DEVELOPMENT);
  });

}).call(this);
