// Generated by CoffeeScript 1.6.3
(function() {
  var init;

  init = function(level) {
    if (level == null) {
      level = Level.PRODUCTION;
    }
    if (level > Level.PRODUCTION) {
      return log("Initialize script");
    }
  };

}).call(this);
